name: Deno Build
run-name: Deno Build ðŸš€
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: ["main", "develop"]

jobs:
  Check-compile:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check format
        run: deno fmt --check

      - name: Run linter
        run: deno task lint

      - name: Unit tests
        run: deno task test

      - name: Compile
        run: deno task compile

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bingo-web
          path: output/bingo-web